layout_spectrum: 0.3373739393427968
typography_spectrum: 0.9554774956777692
color:
  brandStrength: 0.30442061740905046
  lightness: 0.8264137853402644
  saturation: 0.08939747209660709
  rhythmicContrast: 0.8566925954073668
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
name: bold insights. fierce clarity.
title: Sarah Bouker
